### ISSUE TITLE
TreeListView

### ISSUE THREAD

**Issue by jogibear9988** [objorke/PropertyTools#104]
There exists a similar Control here: https://treeviewex.codeplex.com

**Comment by objorke** [comment]
Thanks for the link!
But is this an issue? ;-)

**Comment by jogibear9988** [comment]
no, but there are only issues and pullreq on github as communication platform. i only thought, because that control is the only one you list as not stable

**Comment by jogibear9988** [comment]
I'm now having a Fork of this @ https://github.com/dotnetprojects/TreeViewEx It'a also on Nuget!

**Comment by objorke** [comment]
The link has been added on the wiki https://github.com/objorke/PropertyTools/wiki/TreeListBox
