### ISSUE TITLE
nuget package outdated

### ISSUE THREAD

**Issue by Jonarw** [objorke/PropertyTools#109]
The package available on nuget doesn't seem to be updated anymore. Is this hosted somewhere else now?

Thanks for these awesome tools by the way :)

**Comment by objorke** [comment]
I think there is an issue with the version number
https://ci.appveyor.com/project/objorke/propertytools/build/2015.2.0+501.build.165

**Comment by objorke** [comment]
GitVersion finds 2015.2.0

**Comment by Jonarw** [comment]
I don't know anything about GitVersion, but this file:
https://github.com/objorke/PropertyTools/blob/master/GitVersionConfig.yaml
should cause this, right? Wouldn't it suffice just to remove the `next-version` line?

**Comment by objorke** [comment]
I have started using semantic version numbers, and reset the version number from v2015 to v1. All old versions with high version numbers are unlisted. You need to "downgrade" to v1 - sorry for the inconvenience... https://www.nuget.org/packages/propertytools.wpf/

**Comment by Jonarw** [comment]
No problem at all, thanks a lot for the fix :)
