### ISSUE TITLE
Inserting rows does not work as intended

### ISSUE THREAD

**Issue by Jonarw** [objorke/PropertyTools#135]
To reproduce (with the latest 3.0 preview)
- start the `DataGridDemo `project
- open the `List<PlainObject>` example
- insert a row via right-click > Insert

The new row will be completely empty. Trying to modify this row or adding another row will throw an excepction.
Adding a new row at the bottom via the "+"-sign works as intended.

**Comment by Jonarw** [comment]
Possibly related: Deleting columns via the same right-click menu leaves the deleted row empty until the DataGrid is updated by other means (e.g. adding a new row).

**Comment by Jonarw** [comment]
I found the issue: The problem is the function `GetItemsSourceIndex `in [DataGridOperator.cs ](https://github.com/objorke/PropertyTools/blob/develop/Source/PropertyTools.Wpf/DataGrid/Operators/DataGridOperator.cs)- the part that is marked with `TODO: find a better way to do this` (l.298) seems to cause the problem. If the CollectionView is not yet refreshed, this can throw an IndexOutOfRange Exception.

Replacing the whole function with `return index;` fixes the problem for this special case. At the moment I don't really understand in which cases the ItemsSource index is different from the CollectionView index, so I'm not sure how to fix this.

**Comment by Jonarw** [comment]
An easy fix for both problems would be to insert a `this.CollectionView.Refresh();` before `this.UpdateGridContent();` in `InsertRows()` and `DeleteRows()` in DataGrid.cs. Then the CollectionView is already updated when `GetItemsSourceIndex` is called.

What do you think @objorke ? Do you want a "proper" fix (which I probably couldn't provide), or are you ok with this?

**Comment by objorke** [comment]
thanks for the tip! I added the refresh call in #140

**Comment by Jonarw** [comment]
Awesome! I will test and confirm it works in my project once the Nuget package is updated. Thanks! :)

**Comment by objorke** [comment]
I have pushed the latest build to nuget.org
https://www.nuget.org/packages/PropertyTools.Wpf/3.0.0-unstable0085
