### ISSUE TITLE
Specifying multiple columns with Attributes does not work

### ISSUE THREAD

**Issue by Jonarw** [objorke/PropertyTools#136]
To reproduce:

- Start the `PropertyGridDemo `project
- Click the `Collections `example and switch to `Custom `tab

There should be two columns as defined in the example library, but only one is shown.

I think the problem is that the `PropertyDescriptor `only returns one attribute of a kind. The `ColumnAttribute `class tries to solve that by specifying a unique type id - but only if it's not built as a PCL, which it is in the current PropertyTools configuration.

**Comment by Jonarw** [comment]
Using this derived attribute fixes the problem:

```
    public class ColumnExAttribute : ColumnAttribute
    {
        public ColumnExAttribute(int columnIndex, string propertyName) : base(columnIndex, propertyName)
        {
            this.TypeId = Guid.NewGuid();
        }

        public ColumnExAttribute(int columnIndex, string propertyName, string header) : base(columnIndex, propertyName, header)
        {
            this.TypeId = Guid.NewGuid();
        }

        public ColumnExAttribute(int columnIndex, string propertyName, string header, string formatString, string width = "Auto", char alignment = 'C', bool isReadOnly = false) : base(columnIndex, propertyName, header, formatString, width, alignment, isReadOnly)
        {
            this.TypeId = Guid.NewGuid();
        }

        public override object TypeId { get; }
    }
```

But it seems that this is not possible in a PCL configuration...

**Comment by Jonarw** [comment]
Apparently, the `Attribute.TypeId` property is not available in a portable class library. So it is not possible to retrieve multiple instances of an Attribute set to a single property using the `PropertyDescriptor`.

The only way I can see fixing this, while keeping the PCL configuration and the PropertyDescriptor, would be to define a bunch of Column-derived subclasses, like

```
public class Column1Attribute : ColumnAttribute {}
public class Column2Attribute : ColumnAttribute {}
public class Column3Attribute : ColumnAttribute {}
...
```

It's neither elegant nor ideal, because the number of available columns is always finite...

Apparently, with regular reflection (`PropertyInfo`) it's possible to retrieve multiple instances of attributes, but this would be different to all other parts of PropertyTools, and there is probably a reason to use `PropertyDescriptor`.

Thoughts @objorke ?

**Comment by objorke** [comment]
I don't really like the last idea... :-) There must be a way to read attributes with `AllowMultiple = true` for pcl libraries! Can `PropertyInfo` be used? 

Related links
- https://github.com/objorke/PropertyTools/blob/develop/Source/Examples/PropertyGrid/ExampleLibrary/Examples/CollectionsExample.cs#L49
- https://github.com/objorke/PropertyTools/blob/develop/Source/PropertyTools.Wpf/PropertyGrid/PropertyGridOperator.cs#L486
- https://github.com/objorke/PropertyTools/blob/develop/Source/PropertyTools.Wpf/PropertyGrid/PropertyGridOperator.cs#L386
- https://msdn.microsoft.com/en-us/library/system.attribute.typeid(v=vs.110).aspx
- https://msdn.microsoft.com/en-us/library/system.attributeusageattribute.allowmultiple(v=vs.110).aspx
- https://msdn.microsoft.com/en-us/library/system.reflection.propertyinfo.attributes(v=vs.110).aspx
- https://social.msdn.microsoft.com/Forums/windows/en-US/e6bb4146-eb1a-4c1b-a5b1-f3528d8a7864/propertydescriptorattributes-doesnt-return-all-attributes?forum=winforms

**Comment by objorke** [comment]
If AllowMupltiple is impossible, what about splitting the current attribute into
- `ColumnsAttribute(params string[] properties)`
- `ColumnHeadersAttribute(params string[] headers)`
- `ColumnFormatStringsAttribute(params string[] formatStrings)`
- `ColumnWidthsAttribute(params string[] widths)`
- `ColumnAlignmentsAttribute(params string[] alignments)`

**Comment by Jonarw** [comment]
From what I've read, `PropertyInfo `*should* be able to retrieve multiple Attributes of the same type. But as far as I'm aware, everywhere else in PropertyTools the `TypeDescriptor `is used. I feel like we should stay consistent here, e.g. apparently the TypeDescriptor allows Attributes to be changed at runtime, whereas PropertyInfo doesn't:
[http://stackoverflow.com/a/129369](http://stackoverflow.com/a/129369)

How about something like

```
public class ColumnDefinition
{
    string PropertyName {get; set;}
    string Header {get; set;}
    string FormatString {get;set;}
...
}

ColumnsAttribute(params ColumnDefinition[] columnDefinitions)
```

Would be more convenient to insert/delete columns and closer to the current syntax I think.

**Comment by Jonarw** [comment]
What do you think about the last proposal @objorke ? If you're ok with this I could put together a PR.

Or would you prefer something with `PropertyInfo`?

**Comment by objorke** [comment]
I don´t think the last ctor is possible to use as an attribute.

See
https://github.com/objorke/PropertyTools/blob/develop/Source/PropertyTools/DataAnnotations/ColumnsPropertyAttribute.cs#L24
can´t this attribute be used?

```csharp
[Browsable(false)]
public IEnumerable<ColumnDefinition> ColumnDefinitions { get { ... } }

[ColumnsProperty(nameof(ColumnDefinitions))]
public IEnumerable<Item> { get { ... } }
```

**Comment by Jonarw** [comment]
You are absolutely right regarding the constructor.
I made a commit implementing the column definition your proposed way. The one thing I don't like about it is the possible ambiguity between the "portable" `DataAnnotations.ColumnDefinition` and the `PropertyTools.Wpf.ColumnDefinition` - do you have a clever idea for solving this? I didn't want to use something "clunky" like `PortableColumnDefinition`, but maybe this would be better?
Once you are happy with the implementation I will make a PR.

**Comment by objorke** [comment]
Nice! Great improvement of the example. Could we then remove the `ColumnAttribute`?
Agree the name can be a bit confusing.
What about simply `Column` since the attribute is named `ColumnsPropertyAttribute`?

```csharp
[Browsable(false)]
public IEnumerable<Column> Columns { get { ... } }

[ColumnsProperty(nameof(Columns))]
public IEnumerable<Item> Items { get { ... } }
```

**Comment by Jonarw** [comment]
Yes, the `ColumnAttribute `is already removed.
Made the rename as suggested.
Some examples in the Collections category are still broken, but I think this is because of DataGrid bugs unrelated to this issue.

**Comment by Jonarw** [comment]
Is it possible to push the current develop build to nuget so I can use the recent fixes in my project? Thanks!

**Comment by objorke** [comment]
I just pushed the latest build: 3.0.0-unstable0094
From https://ci.appveyor.com/project/objorke/propertytools/build/3.0.0-unstable.94.build.271/artifacts
