### ISSUE TITLE
Columns specified by attributes are not sorted

### ISSUE THREAD

**Issue by Jonarw** [objorke/PropertyTools#137]
This is marked as TODO in PropertyGridOperator.cs. Will make a pull request with a fix proposition.

**Comment by Jonarw** [comment]
On second thought, this is not really an elegant solution. If I have the time to come up with a better way, I will make another PR.

**Comment by objorke** [comment]
OK! We also need an example to demonstrate this feature.

**Comment by Jonarw** [comment]
An example won't do any good until #136 is fixed, so I will wait to see what solution we can find for that issue...

**Comment by objorke** [comment]
sorry, I think the example
https://github.com/objorke/PropertyTools/blob/develop/Source/Examples/PropertyGrid/ExampleLibrary/Examples/CollectionsExample.cs#L49
should cover both this issue and #136
