### ISSUE TITLE
[DataGrid] Disable AutoFill

### ISSUE THREAD

**Issue by woodlandhunter** [objorke/PropertyTools#143]
Is there a simple way to disable AutoFill? If it's not currently possible, would you accept a patch that added an option to disable the AutoFill handle/functionality?

If you have any direction/brief thoughts on how you'd like it implemented I'd be grateful to have those up front.

Thanks.

**Comment by objorke** [comment]
Yes, this sounds like a good enhancement.
I suggest a dependency property `IsAutoFillEnabled` (alternatives: `UseAutoFill`, `CanAutoFill`, `AutoFillEnabled`, `AutoFillable`, ...)

similar properties
- https://msdn.microsoft.com/en-us/library/system.windows.uielement.ismanipulationenabled(v=vs.110).aspx
- https://msdn.microsoft.com/en-us/library/system.windows.controls.primitives.multiselector.canselectmultipleitems(v=vs.110).aspx

**Comment by objorke** [comment]
when auto fill is disabled, it should not show the auto fill box:
https://github.com/objorke/PropertyTools/blob/develop/Source/PropertyTools.Wpf/DataGrid/DataGrid.cs#L4137
I think it should be enough to not make the box visible!

**Comment by woodlandhunter** [comment]
This is terrific, thank you for implementing it.
