### ISSUE TITLE
PropertyGrid Translation

### ISSUE THREAD

**Issue by RzDeLorean** [objorke/PropertyTools#206]
Hi objorke :)

I have a question about propertygrid ans properties. 

I have a propertygrid bind to a model which contains some properties with english names, I want for these tout be translate in french but I cant. I already tried to assign resx files or change current culture of the thread but its not working.

Can you tell me what's the best way tout translate my properties fromage english to french ?

Thanks ine advance for you answer and your time.

RzDelorean

**Comment by objorke** [comment]
Have you tried using `[DisplayName("....")]`
https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.displaynameattribute?redirectedfrom=MSDN&view=netframework-4.7.2

**Comment by RzDeLorean** [comment]
Yeah I already tried and its not working... 
For my project , the max version of .net framework is 4.6.1 and I cant use any version above ... do you think it can be the problem ? 

Do you have any solution for versions under 4.6.1?

Thanks for your answer and your time,
RzDelorean.

**Comment by RzDeLorean** [comment]
I found the solution, it was a problem with compilation files in my project. Thank you for the help!
