### ISSUE TITLE
Support for Datatable (work in progress,discussions)

### ISSUE THREAD

**Issue by jogibear9988** [objorke/PropertyTools#27]
I'm currently again looking to support DataTable.

For this I think the List Strategy generate Columnsshould be changed to smth. like this:

     var view = CollectionViewSource.GetDefaultView(this.ItemsSource);
                var iitemProperties = view as IItemProperties;
                if (iitemProperties != null)
                {
                    foreach (var info in iitemProperties.ItemProperties)
                    {
                        Owner.ColumnDefinitions.Add(
                            new ColumnDefinition
                            {
                                Descriptor = info.Descriptor as PropertyDescriptor,
                                Header = info.Name,
                                HorizontalAlignment = Owner.DefaultHorizontalAlignment,
                                Width = Owner.DefaultColumnWidth
                            });
                    }

                    return;
                }

what do you mean?

**Comment by objorke** [comment]
Yes, I think there could be a `class ItemPropertiesListOperator : ListOperator` where the `GenerateColumnDefinitions()` method is overridden.
It would be great if we could also support `DataTable`s!

**Comment by jogibear9988** [comment]
https://github.com/objorke/PropertyTools/pull/28

**Comment by objorke** [comment]
Great! 
PS. include the issue number in the pull request description, then this issue will be notified and closed when the PR is merged!
