### ISSUE TITLE
WPF Ext. Toolkit support

### ISSUE THREAD

**Issue by jogibear9988** [objorke/PropertyTools#30]
I'm thinking about support for more Editors in the Datagrid!
(DateTime, TimeSpan, Brush, UpDowns (Decimal,Integer,..))
by including Ext.Wpf Toolkit. 

I've a fork of it at github: https://github.com/dotnetprojects/WpfExToolkit

It's okay when i create a Extension DLL with a new DataGridControlFactory wich uses additional Controls? Will it be possible to include this DLL to the main Project?

**Comment by objorke** [comment]
Great! 
I think this should be in a separate project, so we can use PropertyTools.Wpf without adding additional dependencies. I suggest to name it `PropertyTools.Wpf.Contrib` or `PropertyTools.WpfExToolkit`

**Comment by objorke** [comment]
Also the `PropertyGrid` control could use these editors!

**Comment by jogibear9988** [comment]
Ok, I look to implement it during this week!

**Comment by jogibear9988** [comment]
Solved #75
