### ISSUE TITLE
Enable/disable property by radio button

### ISSUE THREAD

**Issue by objorke** [objorke/PropertyTools#32]
Add an attribute that defines that the header should be a radio button that is bound to a property that enables/disables the decorated property. 

e.g.
``` csharp
        public enum Country { None, Argentina, Bolivia, Chile }

        [Browsable(false)]
        public Country CountrySelector { get; set; }

        [Category("Countries")]
        [EnableByRadioButton("CountrySelector", Country.None)]
        [Comment]
        [DisplayName("None")]
        public string NoneDummy { get { return string.Empty; } }

        [EnableByRadioButton("CountrySelector", Country.Argentina)]
        public string Argentina { get; set; }

        [EnableByRadioButton("CountrySelector", Country.Bolivia)]
        public string Bolivia { get; set; }

        [EnableByRadioButton("CountrySelector", Country.Chile)]
        public string Chile { get; set; }
```

![image](https://cloud.githubusercontent.com/assets/439716/5642278/cdf052a4-9646-11e4-9bc6-c942139cbbf1.png)

**Comment by jogibear9988** [comment]
I would not call it EnableByRadio, i would call it EnableByValue!

**Comment by objorke** [comment]
Sorry, I was not precise enough in the description. There is already an `EnableByAttribute` that does this. But I wanted a feature where there is a radio button in front of the property editor. Currently, we have `OptionalAttribute` that creates a CheckBox, but I would like a similar feature that creates a RadioButton instead.

I know this feature has some limitations - only one property editor for each radio button, but I think it could be useful anyway.

**Comment by objorke** [comment]
What about `[EnableByRadioButton(propertyName,value)]` and `[EnableByCheckBox(propertyName,value)]` and mark `[Optional(propertyName)]` obsolete.

Or `[RadioButtonEnabled(propertyName,value)]`?

Or simply `[RadioButton(propertyName,value)]`?
