### ISSUE TITLE
unusual behavior

### ISSUE THREAD

**Issue by BobRanck** [objorke/PropertyTools#35]
I previously used ver 2014.1.29.1  Recently I updated to version 2015.1.34.0.  With the latest version installed in my project --- any class where I had a reference to both:
          System.ComponentModel
          PropertyTools.DataAnnotations
an error is thrown for every property that has an annotation.
The error reports that the BrowsableAttribute or the DisplayNameAttribute is ambiguous.
This was not the case in the older version.  
The solution for me was to remove the reference to System.ComponentModel, on every class that includes PropertyTools but it is not clear that someone may use some part of System.ComponentModel that is not included in PropertyTools.DataAnnotations.  In any case, for a large project the upgrade requires a lot of hand work when thousands of errors are thrown accompanying the upgrade, so it would probably be nice for others if the ambiguous situation were resolved.

**Comment by objorke** [comment]
I have created #36 and #37 to cover the problems described here. Can we close this issue?

**Comment by BobRanck** [comment]
Thank you, I will watch 36 & 37 - Closed
