### ISSUE TITLE
Doesn't update columns when ObservableCollection<ObservableCollection<T>> change

### ISSUE THREAD

**Issue by juliomrqz** [objorke/PropertyTools#52]
Hello, 

I have some data in a 2D ObservableCollection (ObservableCollection&lt;ObservableCollection&lt;double&gt;&gt;) that can change. When that data change it could have more o less rows and columns, the problem is that the rows get updated but columns don't.

Below is the WPF code I use. I verified that all the bindings are correct, and the item source change correctly.

``` xml
<pt:DataGrid x:Name="CoefficientMatrix"
             ItemsSource="{Binding CoefficientMatrix}"
             ColumnHeadersSource="{Binding CoefficientMatrixColumnHeaders}"
             RowHeadersSource="{Binding CoefficientMatrixRowHeaders}"
             VerticalAlignment="Stretch"
             HorizontalAlignment="Stretch"
             ScrollViewer.CanContentScroll="True"
             ScrollViewer.HorizontalScrollBarVisibility="Auto"
             CanInsert="False"
             CanDelete="False"
             CanResizeColumns="True"
             AutoSizeColumns="True"
             Margin="10"
             Background="White" />
```

Thanks.

**Comment by juliomrqz** [comment]
I created a clean project where you can see the bug
https://github.com/juliomrqz/PropertyToolsBug

**Comment by objorke** [comment]
Great! Sorry I cannot look into the issue myself at the moment.

**Comment by JawadJaber** [comment]
I have noticed this issue is still happening. Any suggestion?
