### ISSUE TITLE
How to set Group.Icon / PropertyIcon dynamically?

### ISSUE THREAD

**Issue by ChristianPerner** [objorke/PropertyTools#63]
I want to set the Group.Icon-Property dynamically. Not a static icon for all categories, it should be individually fo every group/category. I found the PropertyIcon but no Attribute to set it. Any hints?

**Comment by objorke** [comment]
Create a custom "property item factory" to use the group and property icons. Override the `CreateModel` method. 

I think you are right - there is no attribute that supports setting the icon in the `DefaultPropertyItemFactory`.

We can add these features, but then I would like two new issues "Set Group icons by attribute" and "Set property icons by attribute".
