### ISSUE TITLE
Build errors with code downloaded

### ISSUE THREAD

**Issue by uvasag** [objorke/PropertyTools#64]
I'm getting build errors when I downloaded the sourcecode. 

The tag 'ColorToBrushConverter' does not exist in XML namespace 'clr-namespace:PropertyTools.Wpf;assembly=PropertyTools.Wpf'. Line 9 Position 10.	C:\Users\rdoshi\Downloads\PropertyTools-master\PropertyTools-master\Source\Examples\Controls\ControlDemos\Pages\ColorPickerPage.xaml	

It is giving similar errors for all the controls. What am I missing ?

**Comment by objorke** [comment]
The CI build is green, so I think something is wrong on your side. What version of VS are you using?
https://ci.appveyor.com/project/objorke/propertytools

**Comment by objorke** [comment]
Can't be reproduced. Please provide more information and reopen!

**Comment by pipited07** [comment]
@uvasag  I have same question. Could you please tell me how you fix the problem? I use VS2015.
