### ISSUE TITLE
SelectedValuePath is not set when combobox is activated in datagrid.

### ISSUE THREAD

**Issue by ZHZG** [objorke/PropertyTools#66]
Should set SelectedValuePath when showing combobox as edit control in datagrid.

**Comment by objorke** [comment]
Was this solved?
https://github.com/objorke/PropertyTools/commit/3bd51b098f9bf4d3496f48bd37cdcfff47b9c04b

**Comment by ZHZG** [comment]
Yes, I suppose it was fixed. Please see issue #67
