### ISSUE TITLE
Datagrid textbox korean ime bug 

### ISSUE THREAD

**Issue by CHiiLD** [objorke/PropertyTools#69]
solution 

file: DataGrid.cs 

 protected override void OnPreviewKeyDown(KeyEventArgs e)
        {
            base.OnPreviewKeyDown(e);

```
        if (e.Key == Key.ImeProcessed)
        {
            var textEditor = this.currentEditor as TextBox;
            if (textEditor != null && !textEditor.IsFocused)
                this.ShowTextBoxEditControl();
        }
    }
```

I don't know how to pull request.
plz update.

https://github.com/CHiiLD/PropertyTools/commit/ed84fab120ff57b4acad4a7425aa4cfa62f11cb5

**Comment by objorke** [comment]
https://help.github.com/articles/using-pull-requests/

**Comment by objorke** [comment]
Please verify if this solves the bug
