### ISSUE TITLE
MetadataTypeAttribute with PropertyGrid

### ISSUE THREAD

**Issue by julianpaulozzi** [objorke/PropertyTools#70]
Some way to use MetadataTypeAttribute rather than direct attributes in the model to PropertyGrid?

**Comment by objorke** [comment]
This is currently not possible in the default "property item factory" (I am not sure if factory is the right name on this...). But I think it is possible to derive a custom implementation to support this.

**Comment by objorke** [comment]
Can you provide an example how to use the attribute?

**Comment by julianpaulozzi** [comment]
This attribute is particularly useful when you do not have access to base class and want to decorate their properties with DataAnnotations attributes.
The MetadataTypeAttribute attribute enables you to associate a class with a data-model class. In this associated class you provide additional metadata information that is not in the data model.

From: https://msdn.microsoft.com/pt-br/library/system.componentmodel.dataannotations.metadatatypeattribute(v=vs.110).aspx.

I know that this attribute works well to moisturize models in MVC eg, but I never implemented anything that had the same functionality.
I'll give you the example of the recent use case to expose AvalonEdit settings "TextEditorOptions"...

    [DisplayName("Editor Options")]
    [MetadataType(typeof(ExtendedTextEditorOptionsMetadata))]
    public partial class ExtendedTextEditorOptions : TextEditorOptions
    {
    	// My props
    	[FontPreview(14)]
    	public FontFamily FontFamily { get;set; }
    
    	[DisplayName("Font size")]
        [DefaultValue(12)]
        [ItemsSourceProperty("FontSizes")]
    	public double FontSize { get;set; }
    
    	public bool ShowLineNumbers { get;set; }
    }
    
    public class ExtendedTextEditorOptionsMetadata
    {
    	// Base props or others that the name match
    	// Ex. extends base
        [System.ComponentModel.DisplayName("Word wrap indentation")]
        [Spinnable(1, 4, 0, 256), Width(60)]
        public double WordWrapIndentation { get;set; }
    
        // Ex. extends self
        [DefaultValue(true)]
        [DisplayName("Show line numbers rule")]
        public bool ShowLineNumbers { get;set; }
        
        // More code...
    }

**Comment by objorke** [comment]
thanks!

**Comment by julianpaulozzi** [comment]
I thank you, great job.

**Comment by johnsonlu** [comment]
Thanks, this is very interesting!

**Comment by TheMegaMatt** [comment]
Any news on this feature?

**Comment by objorke** [comment]
I am not aware of anyone working on this feature...

**Comment by TheMegaMatt** [comment]
I would work on it but i have no knows then on how to put it back in the
repo
Il 02/ott/2015 01:03 PM "Oystein Bjorke" <notifications@github.com> ha
scritto:

**Comment by TheMegaMatt** [comment]
So after a bit of work i came up with this

https://gist.github.com/TheMegaMatt/2f401440fdea3e77202d

for now it takes the metadata class and creates the form off it. if the metadata is not specified ti will default to the normal behavior. 

Hope this is Helpfull

**Comment by objorke** [comment]
Please make a PR! I will review and merge. Remember to include an example and the contributors file.
Note that I would also like to see the property model refactored, but this is a different issue (#11).

**Comment by TheMegaMatt** [comment]
how do i do it? sorry the dumb question im a newbie on GitHub and opensource in general :P

**Comment by julianpaulozzi** [comment]
- First make a "Fork" (on top of GitHub page) from this to your GitHub.
- Clone "your forked" repository to your machine.
- Make your changes. Avoid changing anything unnecessary and/or project structure. This avoids having to settle unnecessary conflicts.
- Push/Commit all your changes to your repo.
- From there you can go to your repository on github and on "Pull Requests" > "New pull request" and make if to this repo "master".

**Comment by TheMegaMatt** [comment]
How about the contributors file?
Il 03/ott/2015 01:01 AM, "Julian Paulozzi" <notifications@github.com> ha
scritto:

**Comment by TheMegaMatt** [comment]
i was able to do everything from the github app for windows yay :D

**Comment by objorke** [comment]
this should now be supported by default
