### ISSUE TITLE
Display Data in Datagrid

### ISSUE THREAD

**Issue by TheMegaMatt** [objorke/PropertyTools#90]
i have a model that looks like almost like this (it's a simplified version of the real one): 

```c#
using System;

namespace PTSample
{
    public class Person
    {
        public Person(string name) { Name = name; }
        public string Name { get; set; }
    }

    public class Lesson
    {
        public Lesson(DateTime date) { this.Date = date; }
        public DateTime Date { get; set; }
    }

    public class Presence
    {
        public Presence(Person p, Lesson l, bool v)
        {
            Person = p;
            Lesson = l;
            Value = v;
        }

        public Person Person { get; set; }
        public Lesson Lesson { get; set; }
        public bool Value { get; set; }
    }
}
```

i would like to display this model using the Datagrid from this toolkit making it look like this

![test](https://cloud.githubusercontent.com/assets/2596849/10404605/16890d42-6ed4-11e5-9022-f96920ec772a.png)

So that the row shows the the person, the lessons are displayed in the columsn and the boolen "Value" is shown in a checkbox

is this possible?

**Comment by objorke** [comment]
I just created https://gitter.im/objorke/PropertyTools, please ask questions there :-)
Or reformulate the question to a feature request :-)
(The issues section should only be used for bug reports and feature requests.)

A quick answer: the `DataGrid` can be bound to lists, and lists of lists (see the examples!). I think you need to change your model to a "list of lists".

Can we close this issue?
