### ISSUE TITLE
PropertyGrid Localized Enum(>4)

### ISSUE THREAD

**Issue by Diwald** [objorke/PropertyTools#91]
Hi!

I have an Enum in my Settingsclass, when there are only 4 "enumItems" in my Enum, than there are displayed RadioButtons to choose from an they are localized because of my [Description].

That is all fine so far, but when i add a fifth EnumItem to the Enum, there is displayed a Combobox to choose from, but it is not localized, there is "only" the "enumitem"-name.

Is there any solution to solve this problem?

Thanks!

**Comment by objorke** [comment]
Have you seen the property `EnumAsRadioButtonsLimit`? The default value is 4, try setting it higher.
Please close the issue if this solves the problem
