### ISSUE TITLE
Visual Studio 2012 and Demo Project

### ISSUE THREAD

**Issue by wilx01** [objorke/PropertyTools#92]
I am on Visual Studio 2012 and trying to update from an older version of PropertyTools. When I try and Run your demo projects, it will not build, and I am unsure what all the _PCL projects are fo that are stopping my build. These were not present in the older version of Propertytools we have used. Any help getting the Demo Projects to build appreciated

**Comment by wilx01** [comment]
Haveing looked into it more it seems I may need Portable Library Tools, but not sure if I can have them with Windows 7 Visual Studio 2012?

Any help please

**Comment by objorke** [comment]
Yes, support for portable class libraries is required to build this project. 
I think the portable library tools is only needed for VS2010, it should be included in VS 2012/VS 11.0
https://visualstudiogallery.msdn.microsoft.com/b0e0b5e9-e138-410b-ad10-00cb3caf4981/
