### ISSUE TITLE
Make attributes from PropertyTools.DataAnnotations overridable

### ISSUE THREAD

**Issue by dymanoid** [objorke/PropertyTools#93]
I have a suggestion to make overridable all annotation attributes from namespace `PropertyTools.DataAnnotations`.

Currently, we have something like this:

```
public class DescriptionAttribute : Attribute
{
    public string Description { get; private set; }
}
```

I suggest to change it to:

```
public class DescriptionAttribute : Attribute
{
    public virtual string Description { get; protected set; }
}
```

This will allow us to provide custom implementation of data annotations (e.g. localization that can be changed on-the-fly in runtime).

Background: `System.ComponentModel.CategoryAttribute` caches its `Category` property value, so it's impossible to change the value on-the-fly (strictly saying, it's probably possible with reflection, but that's not the intended way to do things). `PropertyTools.DataAnnotations.CategoryAttribute` doesn't allow derived classes to do that either.

**Comment by objorke** [comment]
I have no objections to this. It will not be a breaking change, right?
Please go ahead and make a PR!

**Comment by objorke** [comment]
See the latest version, does it work?
