### ISSUE TITLE
Exception on nullable Enum

### ISSUE THREAD

**Issue by DamDam64** [objorke/PropertyTools#97]
feeding the DataGrid with a nullable enum property produces an exception

BugFix:

``` csharp
class: PropertyTools.Wpf.PropertyDefinition
```

method to fix:

``` csharp
        protected void SetEnumItemsSource()
        {
#if Fix
            this.ItemsSource = Enum.GetValues(this.PropertyType);
#else
            Type propType = this.PropertyType;

            if (propType.IsGenericType &&
                propType.GetGenericTypeDefinition() == typeof(Nullable<>))
            {
                Type[] typeCol = propType.GetGenericArguments();
                Type nullableType;
                if (typeCol.Length > 0)
                {
                    nullableType = typeCol[0];
                    if (nullableType.BaseType == typeof(Enum))
                    {
                        this.ItemsSource = Enum.GetValues(nullableType);
                    }
                }
            }
            else
            {
                this.ItemsSource = Enum.GetValues(propType);
            }
#endif
        }
```

**Comment by objorke** [comment]
Please include a nullable enum in one of the examples and create a PR!

**Comment by DamDam64** [comment]
Hi,

added on is the modified Sample-Demo MainWindow.xaml.cs file. This file 
will produce the Exception.

What did you me with "create a PR"?

Regards
Dietmar

Am 18.02.2016 um 22:42 schrieb Oystein Bjorke:
>
> Please include a nullable enum in one of the examples and create a PR!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/objorke/PropertyTools/issues/97#issuecomment-185934755>.
>


﻿// --------------------------------------------------------------------------------------------------------------------
// <copyright file="MainWindow.xaml.cs" company="PropertyTools">
//   Copyright (c) 2014 PropertyTools contributors
// </copyright>
// <summary>
//   Interaction logic for MainWindow.xaml
// </summary>
// --------------------------------------------------------------------------------------------------------------------
using PropertyTools.DataAnnotations;

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace SimpleDemo
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            this.DataContext = new MainWindowViewModel();
        }

        protected override void OnInitialized(EventArgs e)
        {
            base.OnInitialized(e);

            var data = new TestDictionary();

            this.pgrid2.SelectedObject = new CollectionContainer { Items = data.Values1 };
        }
    }

    // /////////////////////////////////////////////////////
    public class CollectionContainer
    {
        [HeaderPlacement(HeaderPlacement.Collapsed)]    // don't show propertyName
        public ICollection Items { get; set; }
    }

    // /////////////////////////////////////////////////////

    public class TestDictionary
    {
        private Dictionary<int, Item> Dictionary { get; set; }
        public List<Item> Values1
        {
            get
            {
                var result = new List<Item>();
                foreach (var item in Dictionary.Values)
                {
                    result.Add(item);
                }

                return result;
            }
        }

        public object[] Values4
        {
            get
            {
                return this.Values1.ToArray();
            }
        }


        public TestDictionary()
        {
            Dictionary = new Dictionary<int, Item>();

            Dictionary.Add(1, new Item() { Name = "Otto.1", Fraction = 5.1, Number = 21 });
            Dictionary.Add(2, new Item() { Name = "Otto.2", Fraction = 5.2, Number = 22, Test=Item.ETest.Otto });
        }

        public override string ToString()
        {
            return "Dictionary";
        }
    }


    // ////////////////////////////////////////////////////
    public class Item //: PropertyTools.Observable
    {
        public enum ETest
        {
            Hugo,
            Otto,
        }

        public Item()
        {
        }

        private string name;

        private int? number;

        private double? fraction;

        public string Name
        {
            get
            {
                return this.name;
            }
            set
            {
#if Umbau
                this.SetValue(ref name, value, () => Name);
#else
                this.name = value;
#endif
            }
        }

        public int? Number
        {
            get
            {
                return this.number;
            }
            set
            {
#if Umbau
                this.SetValue(ref number, value, () => Number);
#else
                this.number = value;
#endif
            }
        }

        public double? Fraction
        {
            get
            {
                return this.fraction;
            }
            set
            {
#if Umbau
                this.SetValue(ref fraction, value, () => Fraction);
#else
                this.fraction = value;
#endif
            }
        }

        public ETest? Test
        {
            get;
            set;
        }
    }

}

**Comment by objorke** [comment]
PR = pull request
https://help.github.com/articles/using-pull-requests/

**Comment by objorke** [comment]
we need to create an example (in the ExampleLibrary) that reproduces this error.

**Comment by objorke** [comment]
See the Nullable properties example in the DataGridDemo. The "Fruit" column is a nullable enum. There are no exceptions. Use the Delete key to set the value to null.

**Comment by objorke** [comment]
This has been implemented. See the "Nullable properties" example in the DataGridDemo.
